name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        
      - name: Log in to Azure using Azure CLI
        run: |
          az login
      
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name gitpracacr.azurecr.io
      
      - name: Build, tag, and push image to ACR
        run: |
          docker build -t gitpracacr.azurecr.io/my-image:latest .
          docker push gitpracacr.azurecr.io/my-image:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clear pip cache
        run: |
          pip cache purge  # Clear the pip cache to avoid conflicts

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==2.2.3
          pip install "Werkzeug==2.1.2"  # Ensure that the correct version is installed
          pip install -r requirements.txt  # Install other dependencies from requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest test.py
