name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: azure/docker-login@v2
        with:
          login-server: gitpracacr.azurecr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - run: |
          sudo docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          sudo docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clear pip cache
        run: |
          pip cache purge  # Clear the pip cache to avoid conflicts

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==2.2.3
          pip install "Werkzeug==2.1.2"  # Ensure that the correct version is installed
          pip install -r requirements.txt  # Install other dependencies from requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest test.py
